services:

  bot:
    build: bot/
    container_name: bot
    ports:
      - '8070:8080'
    env_file:
      - bot/.env.bot
    environment:
      - POSTGRES_HOST=db

  nginx-entrypoint:
    image: nginx
    container_name: nginx-entrypoint
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    volumes:
      - pgda:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8060:8080

volumes:
  pgda:
