services:
  bot:
    build: ./bot
    container_name: bot
    ports:
      - 8050:80
    env_file:
      - bot/.env
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    ports:
      - 127.0.0.1:8070:8080
    depends_on:
      - db

  agent:
    build: ./agent
    container_name: agent
    ports:
      - 8040:80
    restart: unless-stopped
    env_file:
      - agent/.env

  parser:
    build: ./parser
    container_name: parser
    restart: unless-stopped
    ports:
      - 8060:80
    env_file:
      - .env

  scheduler:
    build: ./scheduler
    container_name: scheduler
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - agent

  selenium_hub:
    image: selenium/standalone-chromium:latest
    container_name: selenium_hub
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
    shm_size: 2g
    env_file:
      - .env

volumes:
  pgdata:
