services:
  bot:
    build: ./bot
    container_name: bot
    env_file:
      - bot/.env.bot
    depends_on:
      - db

  nginx-entrypoint:
    image: nginx
    container_name: nginx-entrypoint
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bot

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    ports:
      - 127.0.0.1:8070:8080
    depends_on:
      - db

volumes:
  pgdata:
