services:
  bot:
    build: bot/
    container_name: bot
    ports:
      - '8070:8080'
    env_file:
      - .env
  nginx-entrypoint:
    image: nginx
    container_name: nginx-entrypoint
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
